const API="/api";let products=[],movements=[],alerts=[];
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function csrfCookie(){const cookie=document.cookie.split(";").map(value=>value.trim()).find(value=>value.startsWith("XSRF-TOKEN="));return cookie?decodeURIComponent(cookie.slice("XSRF-TOKEN=".length)):""}
async function api(path,opt={}){const method=(opt.method||"GET").toUpperCase(),headers={"Content-Type":"application/json",...(opt.headers||{})};if(!["GET","HEAD","OPTIONS"].includes(method)){let token=csrfCookie();if(!token){await fetch(API+"/auth/csrf",{credentials:"same-origin"});token=csrfCookie()}if(token)headers["X-XSRF-TOKEN"]=token}const r=await fetch(API+path,{...opt,method,credentials:"same-origin",headers}),t=await r.text();let d=null;if(t){try{d=JSON.parse(t)}catch{d={message:t}}}if(!r.ok){const error=new Error(d?.message||d?.detail||d?.error||`HTTP ${r.status}`);error.status=r.status;throw error}return d}
function toast(m,e=false){let t=$("toast");t.textContent=m;t.className="toast show"+(e?" error":"");setTimeout(()=>t.className="toast",2600)}
function dt(v){return v?new Date(v).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—"}
function money(v){return "₹"+Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
async function loadAll(){try{[products,movements,alerts]=await Promise.all([api("/products"),api("/stock/movements"),api("/alerts")]);$("backendStatus").textContent="Backend connected";render()}catch(e){if(e.status===401||e.message==="HTTP 401"){$("backendStatus").textContent="Backend connected";$("appShell").hidden=true;$("authScreen").hidden=false;$("toast").className="toast";authMode("login","Your session expired. Sign in again.");return}$("backendStatus").textContent="Backend unavailable";toast("Backend connection failed: "+e.message,true)}}
function render(){ $("statProducts").textContent=products.length;$("statStock").textContent=products.reduce((a,p)=>a+Number(p.currentStock||0),0);$("statAlerts").textContent=alerts.length;$("statMovements").textContent=movements.length;$("alertBadge").textContent=alerts.length;$("alertBadge").style.display=alerts.length?"":"none";bars();dashAlerts();recent();productTable();movementTable();alertPage();selects()}
function bars(){let b=$("stockBars");if(!products.length){b.className="bars empty";b.textContent="No products yet";return}let max=Math.max(...products.map(p=>+p.currentStock||0),1);b.className="bars";b.innerHTML=products.slice(0,8).map(p=>`<div class="bar-wrap"><span class="bar-value">${p.currentStock}</span><div class="bar" style="height:${Math.max(5,(+p.currentStock||0)/max*82)}%"></div><span class="bar-label">${esc(p.name)}</span></div>`).join("")}
function ac(a){let p=a.product||{};return `<div class="alert-card"><div class="alert-symbol">⚠</div><div class="grow"><strong>${esc(p.name||"Product")}</strong><small>Current stock: ${p.currentStock??"—"} · Reorder level: ${p.reorderLevel??"—"}</small></div><button onclick="resolveAlert(${a.id})">Resolve</button></div>`}
function dashAlerts(){$("dashboardAlerts").innerHTML=alerts.length?alerts.slice(0,3).map(ac).join(""):`<div class="empty-state">✓ No active low-stock alerts</div>`}
function recent(){$("recentMovements").innerHTML=movements.length?movements.slice(0,5).map(m=>`<div class="activity"><div class="movement-dot ${m.movementType==="STOCK_IN"?"in":"out"}">${m.movementType==="STOCK_IN"?"+":"−"}</div><div class="activity-main"><strong>${esc(m.product?.name)}</strong><small>${m.movementType.replace("_"," ")} · ${dt(m.movedAt)}</small></div><span class="qty">${m.movementType==="STOCK_IN"?"+":"−"}${m.quantity}</span></div>`).join(""):`<div class="empty-state">No movements recorded</div>`}
function productTable(f=""){let l=products.filter(p=>(p.name+" "+p.productCode).toLowerCase().includes(f.toLowerCase()));$("productsTable").innerHTML=l.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Code</th><th>Product</th><th>Price</th><th>Stock</th><th>Reorder</th><th>Status</th><th>Actions</th></tr></thead><tbody>${l.map(p=>`<tr><td class="code">${esc(p.productCode)}</td><td class="product-name">${esc(p.name)}</td><td>${money(p.price)}</td><td><strong>${p.currentStock}</strong></td><td>${p.reorderLevel}</td><td><span class="status ${p.currentStock<=p.reorderLevel?"low":"ok"}">${p.currentStock<=p.reorderLevel?"Low Stock":"In Stock"}</span></td><td><div class="table-actions"><button class="mini" onclick="stockPrompt(${p.id},'in')">+ IN</button><button class="mini" onclick="stockPrompt(${p.id},'out')">− OUT</button><button class="mini" onclick="editProduct(${p.id})">Edit</button><button class="mini delete" onclick="deleteProduct(${p.id})">Delete</button></div></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state">No products found.</div>`}
function movementTable(){$("movementsTable").innerHTML=movements.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Quantity</th><th>Before</th><th>After</th></tr></thead><tbody>${movements.map(m=>`<tr><td>${dt(m.movedAt)}</td><td class="product-name">${esc(m.product?.name)}</td><td><span class="status ${m.movementType==="STOCK_IN"?"ok":"low"}">${m.movementType.replace("_"," ")}</span></td><td>${m.quantity}</td><td>${m.stockBefore}</td><td>${m.stockAfter}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state">No movements recorded.</div>`}
function alertPage(){$("alertsList").innerHTML=alerts.length?alerts.map(ac).join(""):`<div class="panel empty-state">✓ No active stock alerts.</div>`}
function selects(){["stockInProduct","stockOutProduct"].forEach(id=>$(id).innerHTML=products.map(p=>`<option value="${p.id}">${esc(p.productCode)} — ${esc(p.name)} (Stock: ${p.currentStock})</option>`).join(""))}
function openModal(p=null){$("modal").classList.remove("hidden");$("modalTitle").textContent=p?"Edit Product":"Add Product";$("productId").value=p?.id||"";$("productCode").value=p?.productCode||"";$("productName").value=p?.name||"";$("productPrice").value=p?.price??"";$("productStock").value=p?.currentStock??0;$("productReorder").value=p?.reorderLevel??5}
function closeModal(){$("modal").classList.add("hidden")}
$("addProductBtn").onclick=()=>openModal();$("closeModal").onclick=closeModal;$("cancelModal").onclick=closeModal;
$("modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
$("productForm").onsubmit=async e=>{e.preventDefault();let id=$("productId").value,body={productCode:$("productCode").value.trim(),name:$("productName").value.trim(),price:+$("productPrice").value,currentStock:+$("productStock").value,reorderLevel:+$("productReorder").value};try{await api(id?`/products/${id}`:"/products",{method:id?"PUT":"POST",body:JSON.stringify(body)});closeModal();toast(id?"Product updated":"Product added");loadAll()}catch(x){toast(x.message,true)}};
window.editProduct=id=>openModal(products.find(p=>p.id===id));
window.deleteProduct=async id=>{if(!confirm("Delete this product?"))return;try{await api(`/products/${id}`,{method:"DELETE"});toast("Product deleted");loadAll()}catch(e){toast(e.message,true)}};
window.stockPrompt=async(id,type)=>{let q=prompt(`Enter quantity for Stock ${type==="in"?"IN":"OUT"}:`);if(!q||+q<=0)return;try{await api(`/stock/${id}/${type}`,{method:"POST",body:JSON.stringify({quantity:+q})});toast("Stock updated");loadAll()}catch(e){toast(e.message,true)}};
window.resolveAlert=async id=>{try{await api(`/alerts/${id}/resolve`,{method:"PUT"});toast("Alert resolved");loadAll()}catch(e){toast(e.message,true)}};
$("stockInForm").onsubmit=async e=>{e.preventDefault();try{await api(`/stock/${$("stockInProduct").value}/in`,{method:"POST",body:JSON.stringify({quantity:+$("stockInQty").value})});$("stockInQty").value="";toast("Stock added");loadAll()}catch(x){toast(x.message,true)}};
$("stockOutForm").onsubmit=async e=>{e.preventDefault();try{await api(`/stock/${$("stockOutProduct").value}/out`,{method:"POST",body:JSON.stringify({quantity:+$("stockOutQty").value})});$("stockOutQty").value="";toast("Stock removed");loadAll()}catch(x){toast(x.message,true)}};
$("reportForm").onsubmit=async e=>{e.preventDefault();try{let d=await api(`/reports/fast-moving?from=${$("reportFrom").value}&to=${$("reportTo").value}`),r=Array.isArray(d)?d:(d?.content||[]);$("reportResult").innerHTML=r.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Code</th><th>Quantity</th></tr></thead><tbody>${r.map(x=>`<tr><td class="product-name">${esc(x.product?.name||x.name||"—")}</td><td>${esc(x.product?.productCode||x.productCode||"—")}</td><td>${x.quantity??x.totalQuantity??x.movementCount??"—"}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty-state">No fast-moving products found.</div>`}catch(x){toast(x.message,true)}};
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll("[data-page-jump]").forEach(b=>b.onclick=()=>showPage(b.dataset.pageJump));
function showPage(p){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===p));document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id==="page-"+p));let t={dashboard:["Dashboard","Inventory overview and recent activity"],products:["Products","Manage your inventory catalog"],stock:["Stock Management","Record stock in and stock out transactions"],movements:["Movements","Complete inventory transaction history"],alerts:["Alerts","Low-stock items requiring attention"],reports:["Reports","Analyze fast-moving inventory"]}[p];$("pageTitle").textContent=t[0];$("pageSubtitle").textContent=t[1]}
$("productSearch").oninput=e=>productTable(e.target.value);$("refreshBtn").onclick=()=>{loadAll();toast("Data refreshed")};
let today=new Date(),prior=new Date();prior.setDate(today.getDate()-30);$("reportTo").value=today.toISOString().slice(0,10);$("reportFrom").value=prior.toISOString().slice(0,10);
function authNotice(message,success=false){const notice=$("authNotice");notice.textContent=message;notice.classList.toggle("success",success)}
function authMode(mode,message="",success=false){const registering=mode==="register";$("loginForm").hidden=registering;$("registerForm").hidden=!registering;$("authTitle").textContent=registering?"Create your account":"Welcome back";$("authSubtitle").textContent=registering?"Set up a secure workspace for your inventory.":"Sign in to continue to your workspace.";document.querySelectorAll(".auth-tab").forEach(tab=>{const active=tab.dataset.authMode===mode;tab.classList.toggle("active",active);tab.setAttribute("aria-selected",String(active))});authNotice(message,success)}
function enterWorkspace(user){$("authScreen").hidden=true;$("appShell").hidden=false;$("profileName").textContent=user.name;$("profileEmail").textContent=user.email;$("profileAvatar").textContent=(user.name||"M").trim().charAt(0).toUpperCase();$("apiPort").textContent=location.port||"80";loadAll()}
document.querySelectorAll(".auth-tab").forEach(tab=>tab.onclick=()=>authMode(tab.dataset.authMode));
$("loginForm").onsubmit=async event=>{event.preventDefault();authNotice("");try{const user=await api("/auth/login",{method:"POST",body:JSON.stringify({email:$("loginEmail").value.trim(),password:$("loginPassword").value})});enterWorkspace(user)}catch(error){authNotice(error.message)}};
$("registerForm").onsubmit=async event=>{event.preventDefault();authNotice("");const password=$("registerPassword").value;if(password!==$("registerConfirm").value){authNotice("The passwords do not match.");return}try{const account={name:$("registerName").value.trim(),email:$("registerEmail").value.trim(),password};await api("/auth/register",{method:"POST",body:JSON.stringify(account)});const user=await api("/auth/login",{method:"POST",body:JSON.stringify({email:account.email,password})});enterWorkspace(user)}catch(error){authNotice(error.message)}};
$("logoutBtn").onclick=async()=>{try{await api("/auth/logout",{method:"POST"});$("appShell").hidden=true;$("authScreen").hidden=false;$("loginForm").reset();authMode("login","You have signed out.",true)}catch(error){toast(error.message,true)}};
async function boot(){try{await api("/auth/csrf");const user=await api("/auth/me");if(!user){$("appShell").hidden=true;$("authScreen").hidden=false;$("toast").className="toast";authMode("login");return}enterWorkspace(user)}catch(error){$("appShell").hidden=true;$("authScreen").hidden=false;$("toast").className="toast";authMode("login",error.status&&error.status!==401?"Unable to connect to the backend. Check that the server is running.":"")}}
boot();